name: commit lint

on:
  pull_request:
  
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm install -g @commitlint/cli
          npm install

      - name: Lint commit
        run: commitlint --config .commitlintrc.js --from=HEAD~1