name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetching tags
        run: git fetch --tags -f || true

      - name: Setup Node
        uses: actions/setup-node@v2  # Atualizado para a versão 2 do setup-node
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          # Removido o uso do token aqui, será configurado automaticamente pelo actions/setup-node

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install
        env:
          PUPPETEER_SKIP_DOWNLOAD: true

      - name: Generate Changelog
        id: generate_changelog
        run: |
          changelog=$(npm run changelog:last --silent)
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}" 
          echo -e "set-output name=changelog::${changelog-<empty>}\n"
          echo -e "::set-output name=changelog::${changelog}\n"

      - name: Build API-Docs
        run: npm run generate-api-docs
        continue-on-error: true

      - name: Deploy API-Docs
        uses: peaceiris/actions-gh-pages@v3
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api-docs